import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import _ from "lodash";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/e/e4/Hulu_Logo.svg"
        />
      </Head>

      {/* header */}

      <Header />

      {/*Nav*/}
      <Nav />

      {/*results*/}

      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: JSON.parse(JSON.stringify(request.results)),
    },
  };
}

// function prepareForSerializatoin(obj) {
//   return obj.mapValues(obj, (value) =>
//     typeof value === "undefined" ? null : value
//   );
// }

// export async function getServerSideProps(context) {
//   const genre = context.query.genre;

//   const request = await fetch(
//     `https://api.themoviedb.org/3${
//       requests[genre]?.url || requests.fetchTrending.url
//     }`
//   ).then((res) => res.json());

//   // console.log(JSON.parse(JSON.stringify(request.results)));

//   return prepareForSerializatoin({
//     props: {
//       results: JSON.parse(JSON.stringify(request.results)),
//     },
//   });
// }
